### ISSUE TITLE
Left over helium unused

### ISSUE THREAD

**Issue by ShadowCyclonic** [Grimy/Grimy.github.io#21]
Recently, whenever I import my seed at the end of a run to get my perks upgraded before I portal, the bait perk gets reduced. For example, it tells me to subtract nine from bait. When I subtract nine from bait, I still have exactly enough helium to put nine back into bait, however it continually recommends i remove it from bait, despite having no other places to put that helium

**Comment by Grimy** [comment]
Did you reach z90 recently? z90 is where you unlock the Sci III challenge, which makes Bait completely useless. The points in Bait don’t hurt, but they don’t help either, so Perky just recommends 0 Bait for simplicity’s sake.

If you *didn’t* reach z90 recently, please send your save file so that I can see what’s going wrong.

**Comment by ShadowCyclonic** [comment]
I had a feeling that was it, just wanted to confirm that my helium total wasn't being miscalculated, thank you
