### ISSUE TITLE
helium spend calculation counts bit incorrectly bait cost

### ISSUE THREAD

**Issue by raven0ak** [Grimy/Grimy.github.io#30]
although its not big issue, I note that calc offers 0 bait always, but always also leaves enough helium to buy 1-10 baits (as only available perk)

**Comment by Grimy** [comment]
This is intentional. Bait becomes completely useless at some point, so it’s not worth getting levels in it even if there’s nothing else to do with the helium.

Currently, Perky stops recommending Bait if your target zone is over 70. This might be too early. Do you think changing it to 100 would help?

**Comment by Grimy** [comment]
The point where Perky stops recommending Bait has been changed to zone 90.
