### ISSUE TITLE
Perky calculator result does not show on mac

### ISSUE THREAD

**Issue by wwsangus** [Grimy/Grimy.github.io#4]
I guess this is more like a suggestion rather than a bug report but hear me out.

I have tried using your calculator in my mac and it does not work when I am using it on my mac.

The problem I believe is the display of the perks on the right side of the screen. Since I have tried it on my windows computer, and it works perfectly. And on my Mac, when I import the save into the box the settings below changed accordingly. Hence I am quite certain its the problem with the perks display but I'm not sure if its a Safari or Java or Mac problem.

I play trimps off of my Mac and it's rather annoying to go to my windows computer to refer to your calculator every time i'd like to. So I really hope that there can be some sort of implementation so that the calculator can display properly on mac. 

Thanks so much for this calculator.:)

**Comment by Grimy** [comment]
Unfortunately, I cannot reproduce this issue, since I don’t own a Mac.

* Do you have a recent version of Safari? 10.0 should be enough.

* Are you sure that the results aren’t displayed anywhere? Try scrolling down, they could be there.

* As a workaround, I added another way to access the results. When you’re on Mac, you can now [open the JavaScript console](http://apple.stackexchange.com/questions/58948/how-do-i-open-the-javascript-console-in-safari-6#128478) and read the results there. It’s not as readable as the normal output, but it’s better than nothing.

**Comment by wwsangus** [comment]
I have done as you said. However the issue is still not resolved.

-I have updated my safari to version 10.0.3 but it still did not work.

-I tried scrolling down but I actually can't scroll down on that screen.

-I have opened the JavaScript console and tried to paste my result in. However errors pop up in the console rather than results showing up. I'm not sure why this is happening to this particular set-up but not others. 

Once again, thank you so much for the effort.

Here is a screenshot of the error for your reference.
![screen shot 2017-01-30 at 10 41 42 am](https://cloud.githubusercontent.com/assets/25358994/22410891/ca8b3b12-e6d8-11e6-988c-c87e3c82cc19.png)

**Comment by Grimy** [comment]
Thanks for the info! It seems that my code was triggering [this Safari bug](https://bugs.webkit.org/show_bug.cgi?id=159270). I made a few changes that should avoid triggering the bug; please tell me if it works!

**Comment by wwsangus** [comment]
Nice! It works perfectly now even with the default display! Thank you. :)

**Comment by Grimy** [comment]
Glad to hear it! Thanks for your help in solving this issue (=
