### ISSUE TITLE
"View the source" link goes to minified JS

### ISSUE THREAD

**Issue by pbevin** [Grimy/Grimy.github.io#44]
Prior to the 2.4 release, I used "View the source" to understand how the recommendations worked. Now that it links to the minified JS, it's useful for that.

I'd love to be able to see the human-readable source code if you're willing to release it.

**Comment by Grimy** [comment]
Sorry about that. That’s an unintended consequence of my switching from plain HTML + JS + CSS to Pug + TypeScript + Stylus. This repository now only holds the compiled files; the true sources are [here](https://github.com/Grimy/majig) (silly name because this was initially meant to be a temporary repository).

I changed the “View the source” link to point to the true sources; now working on a better, more permanent solution.

**Comment by Grimy** [comment]
Okay, I moved the sources from the temporary repository to a subfolder in the main repository, and changed the “View the source” link to point to it: https://github.com/Grimy/Grimy.github.io/tree/master/src. I also emptied the temporary and made it redirect to this one. This is a much better setup, I should’ve thought of that earlier.
