### ISSUE TITLE
Cells/s too low when switching from corrupted cell to map

### ISSUE THREAD

**Issue by AI0867** [Grimy/Grimy.github.io#61]
I've found that if I hit a corrupted cell in the world (before magma), my current fighting group dies, I switch to a map and export my save to enter into zFarm **before** a new fighting group starts, the cells/s is far too low, causing zFarm to recommend farming maps several levels lower than normal. Re-exporting after fighting has started on the actual map returns things to normal.

I suspect this is caused by the corrupted cell, possibly because the "current enemy" isn't reset until the next fight starts.

**Comment by Grimy** [comment]
I really don’t think corrupted cells could cause that. Are you maybe switching stances while dead? That’s a known (and unfixable) issue.

**Comment by AI0867** [comment]
That might be it. I'll try to verify that and, if so, close the issue.

How come the stance switch is unfixable?

**Comment by Grimy** [comment]
When switching stances while dead, the game updates the stance, but not the attack value. The information about what stance you *were* in when you died is not anywhere in the save file. It’s not strictly unfixable, since I could recompute attack from scratch, but look at the attack breakdown and you’ll understand why I don’t want to do that.
